# Generated by Django 6.0 on 2025-12-16 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BoldDeskEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('event_type', models.CharField(blank=True, max_length=200)),
                ('payload', models.JSONField()),
            ],
        ),
    ]
